### ISSUE TITLE
cbatticon --version shouldn't need X display

### ISSUE THREAD

**Issue by l0b0** [valr/cbatticon#17]
With the latest version of `cbatticon` I can no longer query for the version without an X display:

    [vagrant@archlinux ~]$ cbatticon --version
    Unable to init server: Could not connect: Connection refused
    Cannot parse command line arguments: Cannot open display: 
    [vagrant@archlinux ~]$ pacman --query cbatticon
    cbatticon 1.4.2-1

**Comment by valr** [comment]
@l0b0 : I've juste fixed this issue.
It will be released soon in 1.5.0

The options that don't require X are:
--version
--list-power-supplies

**Comment by l0b0** [comment]
Thank you!
