### ISSUE TITLE
Ensure a single instance by itself?

### ISSUE THREAD

**Issue by NoviceLive** [valr/cbatticon#32]
This is just a question or probably a feature request.

Do you think it's reasonable for cbatticon to ensure by itself that there's only one instance?
It could behave in this manner by default or via command line options (e.g. `cbatticon --single-instance`).

**Comment by valr** [comment]
@NoviceLive: cbatticon doesn't handle (yet) multiple batteries. Meaning that if you want to follow batt0 and batt1 you'll have to have 2 instances running (one for each battery).

What use case do you see for this option? did you encounter any problem?

Thanks

**Comment by NoviceLive** [comment]
I would get multiple instances of cbatticon if I restart my WM multiple times in older days when I used window managers to spawn it at startup. 

That seems more of a configuration problem of my WM. And nowadays since init managers are used to manage startup applications, the problem doesn't exist any more.

**Comment by valr** [comment]
Indeed, it seems more of a WM problem. I never encountered any problem during reload config or re-exec of openbox.

I'll close this case for now. Let me know if you have any problems.
