### ISSUE TITLE
a little problem when doing make

### ISSUE THREAD

**Issue by DiazVictor** [valr/cbatticon#45]
One small problem, and that is, when I try to make make the output is this:

Package libnotify was not found in the pkg-config search path.
Perhaps you should add the directory containing `libnotify.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libnotify', required by 'virtual:world', not found
Building object cbatticon.o
In file included from /usr/include/gdk/gdkcairo.h:29:0,
                 from /usr/include/gdk/gdk.h:33,
                 from /usr/include/gtk/gtk.h:30,
                 from cbatticon.c:32:
/usr/include/gdk/gdkpixbuf.h:33:35: fatal error: gdk-pixbuf/gdk-pixbuf.h: No such file or directory
 #include <gdk-pixbuf/gdk-pixbuf.h>
                                   ^
compilation terminated.
make: *** [Makefile:79: cbatticon.o] Error 1

**Comment by valr** [comment]
Have you tried building it with:   make WITH_NOTIFY=0

**Comment by valr** [comment]
@DiazVictor, have you tried building with: make WITH_NOTIFY=0
Thanks

**Comment by valr** [comment]
No feedback, closing.

**Comment by CSpencerND** [comment]
> Have you tried building it with: make WITH_NOTIFY=0

Hey, this helped me. Thanks.
