### ISSUE TITLE
Compile on Debian

### ISSUE THREAD

**Issue by Tomas-M** [valr/cbatticon#46]
I would like to compile cbatticon on Debian with GTK2
The problem is that Debian has gtk header files in subdirectories. So while cbatticon expects a file to exist like `/usr/include/glib.h`, Debian has this in `/usr/include/glib-2.0/glib.h`

I have pkg-config, but for some reason it does not catch this.
Is there any parameter for make which would make it work? :)

**Comment by Tomas-M** [comment]
I managed to make it work with the following build command:

    sed -i "s/WITH_GTK3 = 1/WITH_GTK3 = 0/" Makefile
    CFLAGS="-O2 \
    -I/usr/lib/x86_64-linux-gnu/glib-2.0/include/ \
    -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include/ \
    -I/usr/include/gdk-pixbuf-2.0/ \
    -I/usr/include/atk-1.0/ \
    -I/usr/include/cairo \
    -I/usr/include/pango-1.0 \
    -I/usr/include/glib-2.0 \
    -I/usr/include/gtk-2.0" \
    make

**Comment by valr** [comment]
@Tomas-M, I don't know how debian works, can't really help on this.
I see that you've found a manual way to solve the problem, that's good.

What I would propose is that you contact one of the persons having build ppa in launchpad. Just search for 'cbatticon ppa' and you'll find many people having built packages for cbatticon. They might help you more than me.
