### ISSUE TITLE
Unknown icon type: notification

### ISSUE THREAD

**Issue by CGEFMN** [valr/cbatticon#49]
Unknown icon type: notification

>_ cbatticon -i notification
Unknown icon type: notification

But "standard" and symbolic is "fine"

**Comment by valr** [comment]
@CGEFMN, cbatticon -t will list the icon types available on your system. If you don't have any battery icon of type notification in your installed theme(s) then it's normal that it's unknown.

**Comment by valr** [comment]
I don't think there is any action to take on this.
Let me know if you have any problem.

**Comment by GRR3ED** [comment]
Any theme that supports `icon-type notification`?
