### ISSUE TITLE
Hover font size too small on 4K display

### ISSUE THREAD

**Issue by l0b0** [valr/cbatticon#51]
On my 4K laptop monitor the cbatticon icon is about 5 mm tall, which is fine. The hover text, however, is about 1 mm tall, which is unreadable at arms length with good eyesight. The hover text should IMO not enforce any formatting, but should leave that to the desktop environment.

(This *could* conceivably be an Awesome WM issue, but I'm not seeing the same problem with any other status bar widgets.)

**Comment by valr** [comment]
@l0b0 : I'm not setting any font size for the text so it's gtk setting it automatically. Now, because you have different behaviours for other apps there is something to be checked.
Can you tell me which status bar widgets are ok (gtk2/3 ones) on your setup?
Thanks

**Comment by l0b0** [comment]
There's the Awesome WM tags, the keyboard layout widget, cbatticon, the [current time widget](https://gitlab.com/victor-engmark/tilde/blob/dad8e10dc21ccfbfcc1d057f1a11e3ae44b44c97/.config/awesome/rc.lua#L239-240), and the layout icon. Only the layout icon has hover text, and that is properly sized and coloured - white text on a metal gray background, just like the window headers. That's actually another difference with cbatticon - the text background is black.

**Comment by valr** [comment]
Can you send the content of your gtkrc (if you have cbatticon compiled with gtk2) or settings.ini (if cbatticon is compiled with gtk3)?

**Comment by l0b0** [comment]
I'm using [the official Arch Linux package](https://www.archlinux.org/packages/community/x86_64/cbatticon/), so:

```
$ cat /usr/share/gtk-3.0/settings.ini
[Settings]
gtk-icon-theme-name = Adwaita
gtk-theme-name = Adwaita
gtk-font-name = Cantarell 11
```

**Comment by ikarus23** [comment]
Hi I'm using Arch + AwesomeWM and the font is just fine on my HiDPI screen. Of course you have to tell AwesomeWM that you using a HiDPI screen. So the content of my `.Xresources` is:
``` 
Xft.dpi: 168
Xft.autohint: 0
Xft.lcdfilter: lcddefault
Xft.hintstyle: hintfull
Xft.hinting: 1
Xft.antialias: 1
Xft.rgba: rgb
```
Since 96 DPI are the default, 168 is scaling it to 175%. Maybe you want to try 144 (150%) for your screen.

**Comment by l0b0** [comment]
I already set high DPI, but this was one of the few things which didn't scale. But sometime since reporting this it's been fixed.
