### ISSUE TITLE
Possible to have no icon in system tray?

### ISSUE THREAD

**Issue by JPUnD** [valr/cbatticon#54]
Since i like to keep my system tray as simple as possible, and i already have a system icon showing my batter level, would it be possible for me to have no icon is the system tray? If not, is there a workaround to make it not show up?

**Comment by knezi** [comment]
What do you need this for? Is it for the `--command-critical-level` option?
I feel like it's unnecessary to use cbatticon. I believe you should be able to use something like [acpid](https://wiki.archlinux.org/index.php/Acpid).

**Comment by JPUnD** [comment]
Well acpid is more what i was looking for actually, thanks for the info!

Also, one thing i've noticed is that `cbatticon` also runs the command on critical level if the battery is  charging.

Since i have an issue hibernating (my screen acts weird and takes a while to hibernate, still don't know the fix), what would happen is the pc would hibernate (that was the command i gave it to run on critical level), and when i restarted the pc plugged in, it would do the same command once it hit the critical battery level again while charging.
