### ISSUE TITLE
Version number incorrect, still at 1.6.9

### ISSUE THREAD

**Issue by michaelbeaumont** [valr/cbatticon#57]
https://github.com/valr/cbatticon/blob/e4b1ec6b45ff3136bab7672d86b2580d2e93179d/cbatticon.c#L24-L25
```
$ cbatticon --version
cbatticon: a lightweight and fast battery icon that sits in your system tray
version 1.6.9
```

**Comment by valr** [comment]
@michaelbeaumont, thanks!
I have fixed this now as I had to release a new version (1.6.11) including spanish translation.
