### ISSUE TITLE
Wrong icons

### ISSUE THREAD

**Issue by joaopauloalbq** [valr/cbatticon#65]
Instead of _battery-full_, _battery-good_ and _battery-low_ could you use _battery-000_, _battery-010_, _battery-020_ and so on please?

Icons give a much more accurate answer...

![Screenshot_20210726_114718](https://user-images.githubusercontent.com/9905202/127010193-83e78209-b3d4-4392-97e4-674d718abce4.png)

Best regards!

**Comment by valr** [comment]
Closing this issue until hopefully one day there is a standard in the way icons are named (see the closed PR for more info).
